# Generated by Django 6.0 on 2026-01-02 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseignants', to='core.departement')),
            ],
        ),
        migrations.AddField(
            model_name='departement',
            name='faculte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departements', to='core.faculte'),
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('niveau', models.CharField(choices=[('Licence', 'Licence'), ('Master', 'Master'), ('Doctorat', 'Doctorat')], max_length=50)),
                ('duree', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='core.departement')),
            ],
        ),
    ]
