# Generated by Django 6.0 on 2026-01-02 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pageuniversite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageuniversite',
            name='contenu',
        ),
        migrations.AddField(
            model_name='pageuniversite',
            name='historique',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pageuniversite',
            name='missions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pageuniversite',
            name='valeurs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pageuniversite',
            name='titre',
            field=models.CharField(default='Université Exemple', max_length=200),
        ),
    ]
