# Generated by Django 6.0 on 2026-01-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_pageuniversite_contenu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseignant',
            name='email',
        ),
        migrations.AddField(
            model_name='enseignant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='enseignants/'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='specialite',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='grade',
            field=models.CharField(max_length=50),
        ),
    ]
