# Generated by Django 6.0 on 2026-01-02 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_enseignant_email_enseignant_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='core.formation')),
            ],
        ),
    ]
