# Generated by Django 6.0 on 2026-01-02 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_matiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='niveau_detail',
            field=models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2'), ('D', 'Doctorat')], default='L1', max_length=10),
        ),
    ]
