# Generated by Django 6.0 on 2026-01-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_matiere_niveau_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='AxeRecherche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('departements', models.ManyToManyField(blank=True, related_name='axes_recherche', to='core.departement')),
            ],
        ),
    ]
