# Generated by Django 6.0 on 2026-01-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_axerecherche'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('departements', models.ManyToManyField(blank=True, related_name='laboratoires', to='core.departement')),
                ('responsables', models.ManyToManyField(blank=True, related_name='laboratoires', to='core.enseignant')),
            ],
        ),
    ]
