# Generated by Django 6.0 on 2026-01-03 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_laboratoire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300)),
                ('resume', models.TextField(blank=True)),
                ('date_publication', models.DateField()),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='publications/')),
                ('auteurs', models.ManyToManyField(related_name='publications', to='core.enseignant')),
                ('axe_recherche', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='core.axerecherche')),
                ('laboratoire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='core.laboratoire')),
            ],
        ),
    ]
