# Generated by Django 6.0 on 2026-01-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualite',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='actualites/'),
        ),
        migrations.AlterField(
            model_name='actualite',
            name='date_publication',
            field=models.DateField(auto_now_add=True),
        ),
    ]
